
//                                             //
//                                             //
//                 ⌣     ⌣                    //
//                    ‿                        //
//                                             //
//           T R A U M T O N I U M             //
//                                             //
//         Digitales Mixturtrautonium          //
//                                             //
//                                             //
//           Daniel Olbricht · HSD             //
//                                             //
//                                             //







(
//Cursor hier platzieren:
//starten mit cmd+Enter
~projPath = thisProcess.nowExecutingPath.dirname;
s.options.hardwareBufferSize = 64;
loadRelative("serial.scd");
loadRelative("MIDIdefs.scd");
loadRelative("gui.scd");
)




